export const ADD_TO_INPUT = 'ADD_TO_INPUT';
export const HANDLE_EQUAL_TO = 'HANDLE_EQUAL_TO';
export const CLEAR_INPUT = 'CLEAR_INPUT';
export const REMOVE_PREVIOUS_INPUT = 'REMOVE_PREVIOUS_INPUT';
export const HANDLE_OPERATOR = 'HANDLE_OPERATOR';
export const DEFAULT_STATE = 'DEFAULT_STATE';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';